### ISSUE TITLE
anuto crashes on enemy success at high level

### ISSUE THREAD

**Issue by cyBea** [reloZid/android-anuto#158]
With version 0.5 from f-droid I experience crashes in high levels. It happens the third time I start this map from scratch. Now I did a screenshot after reopening and getting to the very wave. If one enemy succeeds in this level the anuto crashes. I only tried this map.

![anuto-crash](https://user-images.githubusercontent.com/5377772/52920461-e5d3d500-330c-11e9-8e14-6cb55d91c91b.jpg)

Thanks for this fun game

**Comment by reloZid** [comment]
Hi, thanks for your report! In v0.5 there was a bug which caused the game to crash if the machine gun tower shoots an enemy which is about to finish. This should be fixed in v0.5-1. Could you verify whether your issue still persists in this version? Thanks.

**Comment by besteiro** [comment]
Hi, i', having crashes too.. i'm on lvl 112 and is always crashing.. i didn't associate why but now from @cyBea  post i can confirm... it's when some enemy gets to finish..

here's some crash report

`java.lang.RuntimeException: Error in game loop!
	at ch.logixisland.anuto.engine.logic.loop.GameLoop.run(GameLoop.java:121)
	at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'float ch.logixisland.anuto.util.math.Vector2.angle()' on a null object reference
	at ch.logixisland.anuto.entity.tower.MachineGun.calcShootingDirection(MachineGun.java:191)
	at ch.logixisland.anuto.entity.tower.MachineGun.tick(MachineGun.java:137)
	at ch.logixisland.anuto.engine.logic.entity.EntityStore.tick(EntityStore.java:53)
	at ch.logixisland.anuto.engine.logic.loop.GameLoop.executeTick(GameLoop.java:139)
	at ch.logixisland.anuto.engine.logic.loop.GameLoop.executeCycle(GameLoop.java:128)
	at ch.logixisland.anuto.engine.logic.loop.GameLoop.run(GameLoop.java:94)`

**Comment by cyBea** [comment]
I can confirm that version 0.5-1 fixes this issue.
