### ISSUE TITLE
Crash after returning from paused state.

### ISSUE THREAD

**Issue by pserwylo** [reloZid/android-anuto#71]
This is on Version 0.2-1 from F-Droid.

To reproduce:
 * Start a new game.
 * Lock your phone (causing anuto to pause).
 * Unlock and open the app again.

Bug:
 * The four buttons to add a new tower at the top of the screen are blank.
 * Touching these blank areas where the buttons _should_ be causes a NPE

```
                         E  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String ch.logixisland.anuto.entity.tower.Tower.getName()' on a null object reference
                         E      at ch.logixisland.anuto.view.game.TowerView.onTouch(TowerView.java:125)
                         E      at android.view.View.dispatchTouchEvent(View.java:8474)
                         E      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                         E      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
                         E      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                         E      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
                         E      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                         E      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
                         E      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                         E      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
                         E      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                         E      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
                         E      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                         E      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
                         E      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                         E      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
                         E      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2625)
                         E      at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1770)
                         E      at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
                         E      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2586)
                         E      at android.view.View.dispatchPointerEvent(View.java:8675)
                         E      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4129)
                         E      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3995)
                         E      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
                         E      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
                         E      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
                         E      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
                         E      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
                         E      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
                         E      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
                         E      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
                         E      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
                         E      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
                         E      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
                         E      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5813)
                         E      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5787)
                         E      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5758)
                         E      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5903)
                         E      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                         E      at android.os.MessageQueue.nativePollOnce(Native Method)
                         E      at android.os.MessageQueue.next(MessageQueue.java:143)
                         E      at android.os.Looper.loop(Looper.java:122)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5294)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at java.lang.reflect.Method.invoke(Method.java:372)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
        ActivityManager  W    Force finishing activity 1 ch.logixisland.anuto/.view.game.GameActivity
```

**Comment by reloZid** [comment]
v0.2-2 (on F-Droid since today) contains some commits for properly initializing all UI stuff if the app returns from being paused (forgot to mention this in the change log). Could you tell me if you are still able to reproduce this bug?

**Comment by pserwylo** [comment]
Oh yes, v0.2-2 did indeed fix this. Thanks :)

**Comment by Tonat** [comment]
>  (forgot to mention this in the change log)

@reloZid I always wondered: is there a changelog (file) for Anuto somewhere? If yes, could it be referenced on F-Droid? Cheers!

**Comment by pserwylo** [comment]
@Tonat: I suspect that [this is a pretty good changelog](https://github.com/reloZid/android-anuto/releases). If that is the case, anyone is free to submit a merge request (i.e. pull request) to https://gitlab.com/fdroid/fdroiddata and add a line to [ch.logixisland.anuto.txt](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/ch.logixisland.anuto.txt):

```
 Changelog:https://github.com/reloZid/android-anuto/releases
```

(see the [F-Droid client metadata](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.fdroid.fdroid.txt) file for an example).

**Comment by Tonat** [comment]
Oh neat, I missed that. Thanks!
